export const footerItems = [
    { itemLabel: "Home", link: "/" },
    { itemLabel: "About Us", link: "/about" },
    { itemLabel: "Services", link: "/services" },
    { itemLabel: "Projects", link: "/projects" },
    { itemLabel: "Blog", link: "/blog" },
    { itemLabel: "Careers", link: "/careers" },
    { itemLabel: "Contact Us", link: "/contact" },
    { itemLabel: "Privacy Policy", link: "/privacy-policy" },
    { itemLabel: "Terms of Service", link: "/terms-of-service" },
    { itemLabel: "FAQ", link: "/faq" },
    { itemLabel: "Support", link: "/support" },
    { itemLabel: "Investor Relations", link: null },
    { itemLabel: "Press & Media", link: null },
    { itemLabel: "Customer Stories", link: null },
    { itemLabel: "Affiliate Program", link: "/affiliate" },
    { itemLabel: "Newsletter", link: null },
    { itemLabel: "Sitemap", link: "/sitemap" },
    { itemLabel: "Partners", link: "/partners" },
    { itemLabel: "API Documentation", link: "/api-docs" },
    { itemLabel: "Community", link: "/community" },
    { itemLabel: "Events", link: "/events" },
    { itemLabel: "Sustainability", link: null },
    { itemLabel: "Accessibility", link: "/accessibility" },
    { itemLabel: "Legal", link: "/legal" },
    { itemLabel: "Trust & Security", link: null },
    { itemLabel: "Developer Resources", link: "/developers" },
];
